### PR TITLE
Implement prompt modifiers

### PR DESCRIPTION
**Pull request by jaresty**
- 'snip' modifies both the prompt and the insertion method
- 'chain' automatically selects the inserted text after so that you can chain prompts together

### CODE REVIEW

**Comment by C-Loftus** [comment]
Made a couple stylistic edits. We don't want to expose actions globally in Talon if we don't need to. And we want to add a few doc strings above any .talon comand. Otherwise this should be all set now. Have not tested it since just got a new OS set up. Should be mainly fine though. 

Thanks for work on this!

Added a contribution.md file to help guide future contributors. Take a look over it and feel free to tweak wording.

**Comment by C-Loftus** [comment]
What did you add? The latest commit added another copy of snip and removed the talon comment. I am fine with both `snip` and `chain`. Just make sure it is all documented and we don't have anything duplicated. Once you are good, feel free to merge.

**Comment by jaresty** [comment]
It's not an exact copy-it doesn't include the prompt. It allows you to apply 'snippet' treatment to your clipboard when you paste using 'model snip clip' which is pretty useful. An alternative that would fit in the existing grammar would be something like 'model snip pass clip', but that didn't seem to work when I tried it. Since we have agreement on the first part of this I will merge what you approved and make a second PR for this change alone.

**Comment by C-Loftus** [comment]
Ok. I think we might need to debug the `pass` command. I feel like there was some other issue with it. Would prefer to use pass until there is a great need.

**Comment by jaresty** [comment]
Ah, I think 'pass' doesn't send the prompt to ChatGPT, which probably explains it.

**Pull request merged**
