### PR TITLE
Cleanup model blend cursorless grammar

### PR DESCRIPTION
**Pull request by jaresty**
- Model blend to <target> didn't specify a source; now it specifies the source as clipboard
- Model blend <target> was only implicitly dropping the 'this'

### CODE REVIEW

**Comment by pokey** [comment]
This seems consistent. I think for convenience it would also be good to have:

- "model paste" or "model paste that"
- "model paste to <target>"

Maybe we already have these. But they would be pretty consistent with "paste that" and "paste to <target>"

**Comment by jaresty** [comment]
I like those. Updated.

**Review by C-Loftus — CHANGES_REQUESTED** [review]
I think we should either use `clip` or `paste` and not have both in the capture. It makes it a bit cleaner to talk about commands when there is one canonical representation for any keywords inside of it.

Let's try to keep non-pipelined commands in a form somewhat similar to 
`model $prompt $textSource $responseMethod` since it makes the mental model easier for the user when everything follows a similar grammar.

So `model blend clip to $cursorless_target` in my opinion is more consistent with this grammar if you are saying it is blending the clipboard as the text source with the cursorless target as the insertion method.

**Comment by jaresty** [comment]
I'm ok with either of these. Can you discuss at the meetup and make a call which way to go? I'll be afk today but I'm ok if you want to make whatever change you agree to and merge it.

**Comment by jaresty** [comment]
If you word prefer I change it, just let me know what to do and I'll put it together tonight if I can find some time. Please feel free to edit it though. The current cursorless blend command is missing a clipboard option so wanted to fix that up.

**Comment by jaresty** [comment]
I think this aligns with the current grammar. I wasn't sure if I should be adding something for 'paste'.

**Review by C-Loftus — APPROVED** [review]

**Comment by C-Loftus** [comment]
Looks good thanks!

**Pull request merged**
