### PR TITLE
Removing thread from modifiers

### PR DESCRIPTION
**Pull request by jaresty**
- We're trying to simplify the grammar
- as the first step in removing the thread from a modifier is to make it available as a setting that can be enabled

### CODE REVIEW

**Comment by jaresty** [comment]
there's still some work to do on removing it - I'll keep working on that later

**Comment by jaresty** [comment]
I thought there was more work to do, but it seems all I had to do was remove it from the modifier list.

**Comment by jaresty** [comment]
Once this is merged I can remove snip and remove the modifier list as well 🔥

**Comment by C-Loftus** [comment]
Good with me. Feel free to merge any of these minor changes we've discussed. As long as it doesn't regress behavior, change user-facing things in a significant way we haven't discussed, or cause a significant internal code refactor, you are good to merge 👍

**Pull request merged**
