### PR TITLE
Custom prompts and easier customization

### PR DESCRIPTION
**Pull request by C-Loftus**
Instead of using a raw talon list, we now use a capture `user.modelPrompt` for all the model commands. The capture is formed via the set union of static prompts and custom prompts. Custom prompts are empty by default. There is an example that can be copied into the user directory from the GPT folder.

The user can create a custom prompt talon list file outside this repo in their user directory and it will automatically be the most specific  (i.e. you don't need to do weird context matching on the hostname or stuff that is semantically meaningless)

### CODE REVIEW

**Comment by C-Loftus** [comment]
@jaresty when you get a chance could you try this out locally and see if you like the UX? Also curious on the naming scheme and if you think customPrompt and modelPrompt both make sense. (as well as static prompt still). 

`modelPrompt = staticPrompt U customPrompt` <- does that seem fair if you had no prior background with this repo? 

If it seems reasonable I will document this in the readme for `GPT/` and then merge

**Comment by jaresty** [comment]
This is great! 😊 I really like the new interface and I think I can use it easily to experiment with new prompts. Thank you for putting this together! 🌟

**Review by jaresty — APPROVED** [review]

**Comment by C-Loftus** [comment]
Sweet will doc this then merge. Just to confirm, did you have a chance to test locally? If not it is ok, just want to know for context

**Comment by jaresty** [comment]
I did give this a try locally and it worked for me.

**Pull request merged**
